name: "Build and release"
on:
  push:
    branches:
    - master
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4

    - name: Set up  vars
      shell: bash
      run: |
         echo "SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 22

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-home-cache-cleanup: true

    - name: Set up Android
      uses: android-actions/setup-android@v3
      with:
        packages: ''

    - name: Build
      run: ./gradlew

    - name: Prepare jar
      if: success()
      id: prepareJar
      run: |
         mv build/libs/abe-all.jar abe-${{ env.SHA_SHORT }}.jar

    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest
        prerelease: false
        files: |
          LICENSE
          abe-${{ env.SHA_SHORT }}.jar
